run-dist:
	./build/install/app/bin/app
inst:
	./gradlew clean
	./gradlew installDist
helpMe:
	./build/install/app/bin/app -h
files:
	./build/install/app/bin/app src/main/java/hexlet/code/file1.json src/main/java/hexlet/code/file2.json
short:
	./build/install/app/bin/app file1.json file2.json
build:
	./gradlew build

.PHONY: build