name: MyOwnActions
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build
        build-root-directory: app 
    - name: Publish code coverage
      uses: paambaati/codeclimate-action@v3.0.0 
      env:
       CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
       #JACOCO_SOURCE_PATH: ./app/src/main/java/hexlet/code
       JACOCO_SOURCE_PATH: src/main/java/hexlet/code ./cc-test-reporter \  
       format-coverage: target/site/jacoco/jacoco.xml\--input-type jacoco ./cc-test-reporter upload-coverage
      with:
       coverageCommand: make report
       workingDirectory: app
       coverageLocations: ${{github.workspace}}/build/reports/jacoco/test/jacocoTestReport.xml:jacoco       
