name: MyOwnActions
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build
        build-root-directory: app 
    - name: Publish code coverage
      uses: paambaati/codeclimate-action@v3.0.0 
      env:
       #CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
       CC_TEST_REPORTER_ID: 7ce9939edc5855026f513fa9753128408de0aa363b6ade6baed905e424a4e322
       JACOCO_SOURCE_PATH: ./app/src/main/java
      with:
       coverageCommand: make report
       workingDirectory: app
       cc-test-reporter after-build --id 7ce9939edc5855026f513fa9753128408de0aa363b6ade6baed905e424a4e322
       coverageLocations: ${{github.workspace}}/build/reports/jacoco/test/jacocoTestReport.xml:jacoco       
